#ifndef STATUS_H
#define STATUS_H

#define COS16_ALL_OK 0
#define COS16_FS_IO_ERROR 1
#define COS16_FS_FILE_NOT_FOUND_ERROR 2
#define COS16_FS_FILE_READ_ONLY_ERROR 3
#define COS16_FS_NOT_US 4
#define COS16_BAD_PATH 5
#define COS16_INVALID_DRIVE 6
#endif